# Generated by Django 3.2.9 on 2021-12-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
